
name: Deploy to Amazon ECS

on:
  push:
    branches: [ "CI/CD" ]
jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List application files
        run: ls -la

  build-docker-image:
    runs-on: ubuntu-latest
    needs: list-files  # This ensures this job runs after the list-files job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
          echo "Docker image built successfully"